services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped

    ports:
      - "80:80"      
      - "443:443"    
      - "81:81"      

    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "${DB_USER}"
      DB_MYSQL_PASSWORD: "${DB_PASSWORD}"
      DB_MYSQL_NAME: "${DB_NAME}"
      DISABLE_IPV6: "true"

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

    depends_on:
      db:
        condition: service_healthy

    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 256M
        reservations:
          memory: 128M

    networks:
      - proxy_net

  db:
    image: mariadb:lts
    container_name: npm-db
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"

    volumes:
      - ./mysql:/var/lib/mysql
      - ./mariadb-custom.cnf:/etc/mysql/conf.d/custom.cnf:ro

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          memory: 128M

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 20s
      interval: 15s
      timeout: 5s
      retries: 5

    networks:
      - proxy_net

networks:
  proxy_net:
    driver: bridge